In [1]:

#PUT THIS FILE IN THE SAME FOLDER OF THE PROJECT DOWNLOADED


from src.circuit.Rotations import *
from src.evaluation.Pauli import H, S, X
from src.utils.r_utils import matmul
import numpy as np

In [2]:
def get_perm_matrix(dimension, nodes, mapping):
    perm = np.zeros((dimension, dimension))

    for i in range(dimension):
        a = [0 for i in range(dimension)]
        b = [0 for i in range(dimension)]
        a[nodes[i]] = 1
        b[mapping[i]] = 1
        narr = np.array(a)
        marr = np.array(b)
        perm = perm + np.outer(marr, narr)

    return perm



In [219]:
dimension = 3

H1 = H( dimension )
X1= X( dimension )
S1 = S( dimension)
HS = matmul(H1.matrix, S1.matrix) 


In [220]:
print(H1.matrix)

match_graph_state = get_perm_matrix(3, [0,1,2], [2, 0, 1])
print ("\n", match_graph_state,"\n",  R( np.pi, -np.pi/2, 0, 1 ,dimension).matrix.round(1))
H1n = matmul( match_graph_state , H1.matrix)
print("\n",H1n)

print("---------------------\n")
R( np.pi, np.pi/2, 0, 1 ,dimension).matrix.round(1)

[[ 0.57735027+0.j   0.57735027+0.j   0.57735027+0.j ]
 [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]]

 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 
 [[ 0.+0.j  1.-0.j  0.+0.j]
 [-1.-0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j]]

 [[ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]
 [ 0.57735027+0.j   0.57735027+0.j   0.57735027+0.j ]]
---------------------



array([[ 0.+0.j, -1.-0.j,  0.+0.j],
       [ 1.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [240]:
t1 = matmul(R( np.pi, -np.pi/2, 0, 1 ,dimension).matrix.round(4), H1n) 

t1.round(2)

array([[ 0.58+0.j , -0.29-0.5j, -0.29+0.5j],
       [-0.58+0.j ,  0.29-0.5j,  0.29+0.5j],
       [ 0.58+0.j ,  0.58+0.j ,  0.58+0.j ]])

In [241]:


# logical 01 physical 12
t2 = matmul(R( -np.pi/2, np.pi/2 +np.pi +np.pi  , 1, 2 ,dimension).matrix.round(4), t1 )

#t2 = matmul(R( np.pi, np.pi/2  , 0 ,1, dimension).matrix.round(4), t2)



t2.round(2)

array([[ 0.58+0.j  , -0.29-0.5j , -0.29+0.5j ],
       [ 0.  +0.j  ,  0.61-0.35j,  0.61+0.35j],
       [ 0.82+0.j  ,  0.2 +0.35j,  0.2 -0.35j]])

In [250]:

t3 = matmul(R( np.pi, -np.pi/2 + 2*np.pi  , 0, 1 ,dimension).matrix.round(4), t2 )#R12->10

t3.round(2)

array([[ 0.  +0.j  ,  0.61-0.35j,  0.61+0.35j],
       [-0.58+0.j  ,  0.29+0.5j ,  0.29-0.5j ],
       [ 0.82+0.j  ,  0.2 +0.35j,  0.2 -0.35j]])

In [251]:
# + np.pi

# logical 02 physical 12
t4 = matmul(R( -1.23 , np.pi/2 + np.pi   +np.pi +2*np.pi , 1 , 2 ,dimension).matrix.round(4), t3 )#R12->10



print(t4.round(2))

[[ 0.  +0.j    0.61-0.35j  0.61+0.35j]
 [-0.  +0.j    0.35+0.61j  0.35-0.61j]
 [ 1.  +0.j    0.  +0.j    0.  -0.j  ]]


In [244]:


# logical 12 physical 01
t5 = matmul( R( np.pi/2, np.pi, 0, 1 ,dimension).matrix.round(4), t4 )#R12->10


t5.round(2)


array([[ 0.  -0.j  , -0.  +0.j  ,  0.87+0.5j ],
       [-0.  +0.j  ,  0.5 +0.87j,  0.  -0.j  ],
       [ 1.  +0.j  ,  0.  +0.j  ,  0.  -0.j  ]])

In [163]:
t5_1= matmul(np.linalg.inv(get_perm_matrix(3, [0, 1, 2], [2, 0, 1]) ), t5)
t5_1.round(2)

array([[ 1.  +0.j  ,  0.  +0.j  ,  0.  -0.j  ],
       [ 0.  -0.j  , -0.87+0.5j ,  0.  +0.j  ],
       [ 0.  +0.j  , -0.  -0.j  , -0.5 +0.87j]])

In [10]:

####### add Rz corrcted accordngly

t6 = matmul( Rz( 2.6100, 0, dimension).matrix.round(4), t5 )#R12->10
t6.round(2)


t7 = matmul( Rz( 2.09 , 1, dimension).matrix.round(4), t6 )#R12->10
t7.round(2)


array([[-0.17-0.37j,  0.05-0.07j,  0.9 +0.09j],
       [-0.41-0.71j,  0.21-0.35j, -0.41-0.j  ],
       [-0.24-0.33j, -0.38+0.82j, -0.09+0.01j]])

In [3]:
dimension = 5

H1 = H(dimension)
S1 = S(dimension)
X1 = X(dimension)
HS = matmul(H1.matrix , S1.matrix)

SH = matmul(S1.matrix, H1.matrix)
XSH = matmul(X1.matrix, SH)
HXSH = matmul(H1.matrix, XSH)
SHXSH = matmul(S1.matrix, HXSH)
SHXSH2 = matmul(SHXSH , SHXSH)






HS2 = matmul(HS, HS)

Xop = X(dimension)
Xop2 = custom_Unitary(matmul(Xop.matrix, Xop.matrix), dimension)

XHS = matmul(Xop.matrix, HS)
XHSop = custom_Unitary(XHS, dimension)
XHS2op = custom_Unitary( matmul(XHS, XHS), dimension)

HSXHS2op = custom_Unitary( matmul(HS, XHS2op.matrix), dimension)


nodes = [ 0, 1, 2, 3, 4]
nmap  =   [ 2, 1, 3, 4, 0]


match_graph_state = get_perm_matrix( dimension, nodes, nmap)
H1n = matmul( match_graph_state , H1.matrix)
print("\n",H1n.round(2))



target = np.array([[-0.    -0.j    ,  0.3779+0.4263j, -0.0551-0.4152j,
        -0.0551+0.4152j,  0.3779-0.4263j],
       [ 0.    -0.j    , -0.2185+0.3008j, -0.5721+0.1859j,
        -0.5721-0.1859j, -0.2185-0.3008j],
       [ 1.    -0.j    ,  0.    +0.j    , -0.    +0.j    ,
        -0.    -0.j    , -0.    -0.j    ],
       [-0.    +0.j    , -0.5344+0.041j ,  0.078 -0.4546j,
         0.078 +0.4546j, -0.5344-0.041j ],
       [ 0.    -0.j    ,  0.1545-0.4755j, -0.4045-0.2939j,
        -0.4045+0.2939j,  0.1545+0.4755j]])
target.round(2)



 [[ 0.45+0.j    0.14-0.43j -0.36-0.26j -0.36+0.26j  0.14+0.43j]
 [ 0.45+0.j    0.14+0.43j -0.36+0.26j -0.36-0.26j  0.14-0.43j]
 [ 0.45+0.j    0.45+0.j    0.45+0.j    0.45+0.j    0.45+0.j  ]
 [ 0.45+0.j   -0.36+0.26j  0.14-0.43j  0.14+0.43j -0.36-0.26j]
 [ 0.45+0.j   -0.36-0.26j  0.14+0.43j  0.14-0.43j -0.36+0.26j]]


array([[-0.  +0.j  ,  0.38+0.43j, -0.06-0.42j, -0.06+0.42j,  0.38-0.43j],
       [ 0.  +0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 1.  +0.j  ,  0.  +0.j  ,  0.  +0.j  , -0.  +0.j  , -0.  +0.j  ],
       [ 0.  +0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.  +0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j]])

In [4]:
#wrong segment

t1 = matmul( R( np.pi, -np.pi/2 , 2, 3 ,dimension).matrix.round(4), target) 

t1.round(2)

array([[ 0.  +0.j  ,  0.38+0.43j, -0.06-0.42j, -0.06+0.42j,  0.38-0.43j],
       [ 0.  +0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  +0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [-1.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ],
       [ 0.  +0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j]])

In [5]:

t2 = matmul(R( np.pi, -np.pi/2 , 2, 4 ,dimension).matrix.round(4), t1) 

t2.round(2)

array([[ 0.  +0.j  ,  0.38+0.43j, -0.06-0.42j, -0.06+0.42j,  0.38-0.43j],
       [ 0.  +0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  +0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j],
       [-1.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ],
       [ 0.  +0.j  ,  0.53-0.04j, -0.08+0.45j, -0.08-0.45j,  0.53+0.04j]])

In [6]:

t3 = matmul(R( -np.pi, -np.pi/2 , 0, 4 ,dimension).matrix.round(4), t2) 

t3.round(2)

array([[ 0.  +0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.  +0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  +0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j],
       [-1.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ],
       [ 0.  +0.j  ,  0.38+0.43j, -0.06-0.42j, -0.06+0.42j,  0.38-0.43j]])

In [11]:

t4 = matmul(R( 1.92, 0.704  , 0, 1 ,dimension).matrix.round(4), t3) 

t4.round(2)

array([[ 0.  +0.j  , -0.38-0.27j,  0.23-0.72j,  0.46+0.j  , -0.  -0.j  ],
       [ 0.  +0.j  , -0.43-0.14j, -0.  -0.09j, -0.57+0.18j, -0.38-0.53j],
       [ 0.  +0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j],
       [-1.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ,  0.  +0.j  ],
       [ 0.  +0.j  ,  0.38+0.43j, -0.06-0.42j, -0.06+0.42j,  0.38-0.43j]])

In [29]:
 R( 0, 0, 2, 3 ,dimension).matrix

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [49]:
z = R( 0,0, 2, 4 ,dimension).matrix 

#z = matmul( R( np.pi, -np.pi/2 , 2, 3 ,dimension).matrix, z)

z = matmul( R( np.pi, -np.pi/2 -np.pi, 2, 3 ,dimension).matrix, z )

z = matmul( R( np.pi, -np.pi/2 , 2, 4 ,dimension).matrix  ,z)
z = matmul( R( -np.pi, -np.pi/2 -np.pi, 0, 4 ,dimension).matrix ,z)

z = matmul( R( 1.92, 0.704, 0, 1 ,dimension).matrix ,z)


z = matmul( R( -np.pi, np.pi/2 -np.pi, 0, 4 ,dimension).matrix ,z)
z = matmul( R( np.pi, np.pi/2 -np.pi, 2, 4 ,dimension).matrix  ,z)

#z = matmul( R( np.pi, np.pi/2 -np.pi, 2, 3 ,dimension).matrix,z)

z = matmul( R( np.pi, np.pi/2 , 2, 3 ,dimension).matrix,z)

z.round(1)

array([[ 1. +0.j , -0. -0.j ,  0. +0.j , -0. +0.j , -0. -0.j ],
       [ 0. -0.j ,  0.6+0.j , -0.5+0.6j, -0. -0.j ,  0. -0.j ],
       [-0. -0.j , -0.5-0.6j, -0.6+0.j ,  0. -0.j ,  0. +0.j ],
       [-0. +0.j , -0. +0.j ,  0. +0.j ,  1. -0.j , -0. -0.j ],
       [-0. -0.j , -0. -0.j , -0. +0.j ,  0. -0.j , -1. +0.j ]])

In [50]:
R( 1.92, -0.704  , 1, 2 ,dimension).matrix.round(1)

array([[ 1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0.6+0.j ,  0.5-0.6j,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j , -0.5-0.6j,  0.6+0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ]])

In [166]:
def newMod(a,b = 2*np.pi):
    res = np.mod(a,b)
    return res if not res else res-b if a<0 else res

def Pi_mod(a):
    a = newMod(a)
    print(a)
    if(a > 0 and a>np.pi):
        a = a - 2*np.pi
    elif(a < 0 and abs(a)>np.pi):
        a = 2*np.pi+a
        
    return a

Pi_mod(5*np.pi/4)

3.9269908169872414


-2.356194490192345

### Commutation of phase and pi pulse

In [317]:
matmul(Rz(np.pi, 1, dimension).matrix, R( np.pi, np.pi/2  , 0, 1 ,dimension).matrix.round(1)).round(2)

array([[ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]])

In [323]:
print(R( np.pi, np.pi/2  , 0, 1 ,dimension).matrix.round(1))
matmul( R( np.pi, np.pi/2  , 0, 1 ,dimension).matrix.round(1), Rz(np.pi,1,dimension).matrix).round(2)

[[ 0.+0.j -1.-0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 1.-0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]]


array([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [295]:
#comuting
x = matmul( R( np.pi, -np.pi/2 , 1,2 ,dimension).matrix.T.conj(), R( np.pi, -np.pi/2 , 0,4 ,dimension).matrix.T.conj()).round(2)
print(x)
print()
print(matmul(Rz(np.pi, 1,dimension).matrix, x).round(2))
print()
print(matmul(Rz(np.pi, 0,dimension).matrix, x).round(2))

[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]

[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]

[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]


In [292]:
#non comm
x = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix.T.conj(), R( np.pi, -np.pi/2 , 0,4 ,dimension).matrix.T.conj()).round(2)
print(x)
print(matmul(Rz(np.pi, 0,dimension).matrix, x).round(2))
print(matmul(Rz(np.pi, 1,dimension).matrix, x).round(2))

[[ 0.+0.j -1.+0.j  0.+0.j  0.+0.j -0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
[[ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
[[ 0.+0.j -1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]


In [279]:
R( np.pi, np.pi/2  , 0, 1 ,dimension).matrix.round(1)

array([[ 0.+0.j, -1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]])

### Retrieval dimension 5

In [376]:
nodes = [ 0, 1, 2, 3, 4]
nmap  = [ 2, 1, 3, 4, 0]

target = H1.matrix


In [377]:
#logical 01 

zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)

In [378]:
match_graph_stateLtoP = get_perm_matrix( dimension, nodes, nmap)

z = matmul( match_graph_stateLtoP , target)

#logical 01 phy 24

z = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2  , 0,4 ,dimension).matrix, z )

z = matmul( R( -np.pi/2, -np.pi/2  , 2,4 ,dimension).matrix, z) #t flip


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
match_graph_stateP2L1 = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix.T.conj(), R( np.pi, -np.pi/2 , 0,4 ,dimension).matrix.T.conj())
match_graph_stateP2L1 = abs(matmul( match_graph_stateLtoP.conj().T , match_graph_stateP2L1))  
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( Rz( np.pi, 1 ,dimension).matrix ,z)
z = matmul( Rz(np.pi, 4, dimension).matrix, z)

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( match_graph_stateP2L1, z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )



[[ 0.632-0.j     0.414+0.301j  0.06 +0.186j  0.06 -0.186j  0.414-0.301j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.447+0.j    -0.362+0.263j  0.138-0.425j  0.138+0.425j -0.362-0.263j]
 [ 0.447-0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.632-0.j     0.414+0.301j  0.06 +0.186j  0.06 -0.186j  0.414-0.301j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.447+0.j    -0.362+0.263j  0.138-0.425j  0.138+0.425j -0.362-0.263j]
 [ 0.447+0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [379]:
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl.round(2)

array([[ 0.77-0.j  ,  0.13+0.4j ,  0.13-0.09j,  0.13+0.09j,  0.13-0.4j ],
       [ 0.  -0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  -0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.45+0.j  , -0.36-0.26j,  0.14+0.43j,  0.14-0.43j, -0.36+0.26j],
       [ 0.45+0.j  ,  0.14-0.43j, -0.36-0.26j, -0.36+0.26j,  0.14+0.43j]])

In [380]:
z = matmul( match_graph_state , target)

#logical 01 phy 24 + l 02 phy 23

z = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2  , 0,4 ,dimension).matrix, z )

z = matmul( R( -np.pi/2, -np.pi/2 , 2,4 ,dimension).matrix ,z) #t flip

#---

z = matmul( R( 1.23, -np.pi/2 , 2,3 ,dimension).matrix ,z) #t flip # single rotation commuting with pi pulses

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
match_graph_stateP2L2 = matmul( R( np.pi, np.pi/2 , 0,1 ,dimension).matrix.T.conj(), R( np.pi, np.pi/2 , 0,4 ,dimension).matrix.T.conj())
match_graph_stateP2L2 = abs(matmul( match_graph_stateLtoP.conj().T , match_graph_stateP2L2))  
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( Rz( np.pi, 1 ,dimension).matrix ,z)
z = matmul( Rz(np.pi, 4, dimension).matrix, z)

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( match_graph_stateP2L2 , z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )

[[ 0.775-0.j     0.129+0.397j  0.129-0.094j  0.129+0.094j  0.129-0.397j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.447-0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.775-0.j     0.129+0.397j  0.129-0.094j  0.129+0.094j  0.129-0.397j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.447+0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [381]:
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl = matmul( R( 1.04, -np.pi/2 , 0,3 ,dimension).matrix , zl)

zl.round(2)

array([[ 0.89-0.j  , -0.07+0.21j,  0.18+0.13j,  0.18-0.13j, -0.07-0.21j],
       [ 0.  -0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  -0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.  -0.j  , -0.38-0.43j,  0.06+0.42j,  0.06-0.42j, -0.38+0.43j],
       [ 0.45+0.j  ,  0.14-0.43j, -0.36-0.26j, -0.36+0.26j,  0.14+0.43j]])

In [344]:
z = matmul( match_graph_state , target)

#logical 01 phy 24 + l 02 phy 23

z = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2  , 0,4 ,dimension).matrix, z )

z = matmul( R( -np.pi/2, -np.pi/2 , 2,4 ,dimension).matrix ,z) #t flip

#---

z = matmul( R( 1.23, -np.pi/2 , 2,3 ,dimension).matrix ,z) #single rotation commuting with pi pulses

#-------

z = matmul( R( np.pi, -np.pi/2 +np.pi , 0,4 ,dimension).matrix, z)

z = matmul( R( -1.04, -np.pi/2 +np.pi, 2,4 ,dimension).matrix, z) #t flip



#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
match_graph_stateP2L3 = abs(matmul( match_graph_stateP2L2, R( np.pi, -np.pi/2, 0,4  ,dimension).matrix.T.conj()))
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

#z = matmul( Rz(np.pi, 0, dimension).matrix, z)
z = matmul( Rz(np.pi, 1 ,dimension).matrix ,z)
#z = matmul( Rz(np.pi, 4, dimension).matrix, z)
#--

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( match_graph_stateP2L3 , z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )

[[ 0.894-0.j    -0.068+0.214j  0.181+0.13j   0.181-0.13j  -0.068-0.214j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.894-0.j    -0.068+0.214j  0.181+0.13j   0.181-0.13j  -0.068-0.214j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [352]:
### ROTATION 57
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl = matmul( R( 1.04, -np.pi/2 , 0,3 ,dimension).matrix , zl)
zl = matmul( R( 0.92, -np.pi/2 , 0,4 ,dimension).matrix , zl)

print(zl.round(3))

[[ 1.   -0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004-0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]


In [353]:
z = matmul( match_graph_state , target)

#logical 01 phy 24 + l 02 phy 23

z = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2  , 0,4 ,dimension).matrix, z )

z = matmul( R( -np.pi/2, -np.pi/2 , 2,4 ,dimension).matrix ,z) #t flip

#---

z = matmul( R( 1.23, -np.pi/2 , 2,3 ,dimension).matrix ,z) #single rotation commuting with pi pulses

#-------

z = matmul( R( np.pi, -np.pi/2 +np.pi , 0,4 ,dimension).matrix, z)

z = matmul( R( -1.04, -np.pi/2 +np.pi, 2,4 ,dimension).matrix, z) #t flip

#-------
z = matmul( R( np.pi, -np.pi/2 +np.pi, 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2 , 0,4 ,dimension).matrix, z )

z = matmul( R( -0.92, -np.pi/2 , 2,4 ,dimension).matrix, z) #t flip




#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
fixer = abs( matmul( R( np.pi, -np.pi/2 +np.pi, 0,1,dimension).matrix.T.conj(), R( np.pi, -np.pi/2, 0,4  ,dimension).matrix.T.conj()) ) 
match_graph_stateP2L4 = matmul( match_graph_stateP2L3, fixer)
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

#z = matmul( Rz(np.pi, 0, dimension).matrix, z)
#z = matmul( Rz(np.pi, 1 ,dimension).matrix ,z)
z = matmul( Rz(np.pi, 4, dimension).matrix, z)
#--

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( match_graph_stateP2L4 , z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )

[[ 1.   -0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004+0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

[[ 1.   -0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004-0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

True


In [370]:
### ROTATION 71
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl = matmul( R( 1.04, -np.pi/2 , 0,3 ,dimension).matrix , zl)
zl = matmul( R( 0.92, -np.pi/2 , 0,4 ,dimension).matrix , zl)
zl = matmul( R( 1.92876554508012, -0.7048717707030305 ,   1,2 ,dimension).matrix , zl)


print(zl.round(3))

[[ 1.   -0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.383+0.528j -0.569-0.185j  0.   +0.087j -0.435+0.141j]
 [ 0.   -0.j     0.   +0.j     0.465-0.j     0.233+0.716j -0.376+0.273j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004-0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]


In [375]:
z = matmul( match_graph_state , target)

#logical 01 phy 24 + l 02 phy 23

z = matmul( R( np.pi, -np.pi/2 , 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2  , 0,4 ,dimension).matrix, z )

z = matmul( R( -np.pi/2, -np.pi/2 , 2,4 ,dimension).matrix ,z) #t flip

#---

z = matmul( R( 1.23, -np.pi/2 , 2,3 ,dimension).matrix ,z) #single rotation commuting with pi pulses

#-------

z = matmul( R( np.pi, -np.pi/2 +np.pi , 0,4 ,dimension).matrix, z)

z = matmul( R( -1.04, -np.pi/2 +np.pi, 2,4 ,dimension).matrix, z) #t flip

#-------
z = matmul( R( np.pi, -np.pi/2 +np.pi, 0,1 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2 , 0,4 ,dimension).matrix, z )

z = matmul( R( -0.92, -np.pi/2 , 2,4 ,dimension).matrix, z) #t flip

#------------
z = matmul( R( np.pi, -np.pi/2 , 2,3 ,dimension).matrix, z)
z = matmul( R( np.pi, -np.pi/2 +np.pi, 2,4 ,dimension).matrix, z )
z = matmul( R( -np.pi, -np.pi/2 +np.pi, 0,4 ,dimension).matrix, z)# theta flip  ???

z = matmul( R( 1.92876554508012, 0.7048717707030305, 0,1 ,dimension).matrix, z )# phi flip -no theta flip-



#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
fixer = abs( matmul( R( -np.pi, -np.pi/2 +np.pi, 0,4, dimension).matrix.T.conj(), R( 0, 0, 0,4  ,dimension).matrix)) 
fixer = abs( matmul( R( np.pi, -np.pi/2 +np.pi, 2,4,dimension).matrix.T.conj(), fixer) )
fixer = abs( matmul(  R( np.pi, -np.pi/2 , 2,3 ,dimension).matrix.T.conj(), fixer ) )
            
match_graph_stateP2L5 = matmul( match_graph_stateP2L4, fixer)
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

#z = matmul( Rz(np.pi, 0, dimension).matrix, z)
#z = matmul( Rz(np.pi, 1 ,dimension).matrix ,z)
z = matmul( Rz(np.pi, 3, dimension).matrix, z)
z = matmul( Rz(np.pi, 4, dimension).matrix, z)
#--

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


z = matmul( match_graph_stateP2L5 , z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )

[[ 1.   +0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.383+0.528j -0.569-0.185j  0.   +0.087j -0.435+0.141j]
 [ 0.   -0.j     0.   +0.j     0.465-0.j     0.233+0.716j -0.376+0.273j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004+0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

[[ 1.   -0.j     0.001+0.003j  0.001-0.j     0.001+0.j     0.001-0.003j]
 [ 0.   -0.j    -0.383+0.528j -0.569-0.185j  0.   +0.087j -0.435+0.141j]
 [ 0.   -0.j     0.   +0.j     0.465-0.j     0.233+0.716j -0.376+0.273j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.004-0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

True


In [82]:
nodes = [ 0, 1, 2, 3, 4]
nmap =   [ 3, 2, 1, 4, 0]

target = H1.matrix


In [83]:
#logical 01 

zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
print(zl.round(2))

[[ 0.63-0.j    0.41+0.3j   0.06+0.19j  0.06-0.19j  0.41-0.3j ]
 [ 0.  -0.j   -0.22+0.3j  -0.57+0.19j -0.57-0.19j -0.22-0.3j ]
 [ 0.45+0.j   -0.36+0.26j  0.14-0.43j  0.14+0.43j -0.36-0.26j]
 [ 0.45+0.j   -0.36-0.26j  0.14+0.43j  0.14-0.43j -0.36+0.26j]
 [ 0.45+0.j    0.14-0.43j -0.36-0.26j -0.36+0.26j  0.14+0.43j]]


In [84]:
match_graph_stateLtoP = get_perm_matrix( dimension, nodes, nmap)

z = matmul( match_graph_stateLtoP , target)

#logical 01 phy 24

z = matmul( R( np.pi, -np.pi/2 , 2,4 ,dimension).matrix, z)

z = matmul( R( -np.pi/2, -np.pi/2  , 3, 4 ,dimension).matrix, z) #t flip


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
match_graph_stateP2L1 = abs(matmul( match_graph_stateLtoP.T.conj(), R( np.pi, -np.pi/2 , 2,4 ,dimension).matrix.T.conj()) ) 
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( Rz(np.pi, 4, dimension).matrix, z)

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( match_graph_stateP2L1, z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )



[[ 0.632+0.j     0.414+0.301j  0.06 +0.186j  0.06 -0.186j  0.414-0.301j]
 [ 0.   +0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.447+0.j    -0.362+0.263j  0.138-0.425j  0.138+0.425j -0.362-0.263j]
 [ 0.447-0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.632-0.j     0.414+0.301j  0.06 +0.186j  0.06 -0.186j  0.414-0.301j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.447+0.j    -0.362+0.263j  0.138-0.425j  0.138+0.425j -0.362-0.263j]
 [ 0.447+0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [85]:
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl.round(2)

array([[ 0.77-0.j  ,  0.13+0.4j ,  0.13-0.09j,  0.13+0.09j,  0.13-0.4j ],
       [ 0.  -0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  -0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.45+0.j  , -0.36-0.26j,  0.14+0.43j,  0.14-0.43j, -0.36+0.26j],
       [ 0.45+0.j  ,  0.14-0.43j, -0.36-0.26j, -0.36+0.26j,  0.14+0.43j]])

In [86]:
match_graph_stateLtoP = get_perm_matrix( dimension, nodes, nmap)

z = matmul( match_graph_stateLtoP , target)

#logical 01 

z = matmul( R( np.pi, -np.pi/2 , 2,4 ,dimension).matrix, z)

z = matmul( R( -np.pi/2, -np.pi/2  , 3, 4 ,dimension).matrix, z) #t flip
#---
#logical 02
z = matmul( R( np.pi, -np.pi/2 , 1,2 ,dimension).matrix, z)
z = matmul( R( -np.pi, -np.pi/2 +np.pi , 2,4 ,dimension).matrix, z)# t flip

z = matmul( R( -1.23, -np.pi/2 +np.pi, 3,4 ,dimension).matrix, z)# t flip

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

fixer = abs(matmul( match_graph_stateP2L1 , R( np.pi, -np.pi/2 , 1,2 ,dimension).matrix.T.conj()) )

match_graph_stateP2L2 = abs(matmul(fixer,  R( -np.pi, -np.pi/2 +np.pi, 2,4 ,dimension).matrix.T.conj() ) )
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( Rz(np.pi, 2, dimension).matrix, z)

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( match_graph_stateP2L2, z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z- zl) < 1e-6).all() )



[[ 0.775+0.j     0.129+0.397j  0.129-0.094j  0.129+0.094j  0.129-0.397j]
 [ 0.   +0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   +0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.447-0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.775-0.j     0.129+0.397j  0.129-0.094j  0.129+0.094j  0.129-0.397j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.447+0.j    -0.362-0.263j  0.138+0.425j  0.138-0.425j -0.362+0.263j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [87]:
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl = matmul( R( 1.04, -np.pi/2 , 0,3 ,dimension).matrix , zl)

zl.round(2)

array([[ 0.89-0.j  , -0.07+0.21j,  0.18+0.13j,  0.18-0.13j, -0.07-0.21j],
       [ 0.  -0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  -0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.  -0.j  , -0.38-0.43j,  0.06+0.42j,  0.06-0.42j, -0.38+0.43j],
       [ 0.45+0.j  ,  0.14-0.43j, -0.36-0.26j, -0.36+0.26j,  0.14+0.43j]])

In [92]:
match_graph_stateLtoP = get_perm_matrix( dimension, nodes, nmap)

z = matmul( match_graph_stateLtoP , target)

#logical 01 

z = matmul( R( np.pi, -np.pi/2 , 2,4 ,dimension).matrix, z)

z = matmul( R( -np.pi/2, -np.pi/2  , 3, 4 ,dimension).matrix, z) #t flip
#---
#logical 02
z = matmul( R( np.pi, -np.pi/2 , 1,2 ,dimension).matrix, z)
z = matmul( R( -np.pi, -np.pi/2 +np.pi , 2,4 ,dimension).matrix, z)# t flip

z = matmul( R( -1.23, -np.pi/2 +np.pi, 3,4 ,dimension).matrix, z)# t flip

#---
#logical 03
z = matmul( R( np.pi, -np.pi/2 +np.pi, 1,2 ,dimension).matrix, z)
z = matmul( R( -np.pi, -np.pi/2 -np.pi, 2,4 ,dimension).matrix, z)# t flip

z = matmul( R( -1.04, -np.pi/2, 3,4 ,dimension).matrix, z)# t flip


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
f = abs( matmul( R( np.pi, -np.pi/2 +np.pi, 1,2 ,dimension).matrix.T.conj(), R( -np.pi, -np.pi/2 -np.pi, 2,4 ,dimension).matrix.T.conj() ))

match_graph_stateP2L3 = abs( matmul(  match_graph_stateP2L2  , f  ) )
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( Rz(np.pi, 4, dimension).matrix, z)
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( match_graph_stateP2L3, z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z - zl) < 1e-6).all() )



[[ 0.894+0.j    -0.068+0.214j  0.181+0.13j   0.181-0.13j  -0.068-0.214j]
 [ 0.   +0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   +0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

[[ 0.894-0.j    -0.068+0.214j  0.181+0.13j   0.181-0.13j  -0.068-0.214j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.447+0.j     0.138-0.425j -0.362-0.263j -0.362+0.263j  0.138+0.425j]]

True


In [93]:
zl = matmul( R( np.pi/2, -np.pi/2 , 0,1 ,dimension).matrix , H1.matrix)
zl = matmul( R( 1.23, -np.pi/2 , 0,2 ,dimension).matrix , zl)
zl = matmul( R( 1.04, -np.pi/2 , 0,3 ,dimension).matrix , zl)
zl = matmul( R( 0.9272952180016122, -np.pi/2 , 0,4 ,dimension).matrix , zl)

zl.round(2)

array([[ 1.  -0.j  ,  0.  +0.j  , -0.  -0.j  , -0.  +0.j  ,  0.  -0.j  ],
       [ 0.  -0.j  , -0.22+0.3j , -0.57+0.19j, -0.57-0.19j, -0.22-0.3j ],
       [ 0.  -0.j  , -0.53+0.04j,  0.08-0.45j,  0.08+0.45j, -0.53-0.04j],
       [ 0.  -0.j  , -0.38-0.43j,  0.06+0.42j,  0.06-0.42j, -0.38+0.43j],
       [ 0.  -0.j  ,  0.15-0.48j, -0.4 -0.29j, -0.4 +0.29j,  0.15+0.48j]])

In [95]:
match_graph_stateLtoP = get_perm_matrix( dimension, nodes, nmap)

z = matmul( match_graph_stateLtoP , target)

#logical 01 

z = matmul( R( np.pi, -np.pi/2 , 2,4 ,dimension).matrix, z)

z = matmul( R( -np.pi/2, -np.pi/2  , 3, 4 ,dimension).matrix, z) #t flip
#---
#logical 02
z = matmul( R( np.pi, -np.pi/2 , 1,2 ,dimension).matrix, z)
z = matmul( R( -np.pi, -np.pi/2 +np.pi , 2,4 ,dimension).matrix, z)# t flip

z = matmul( R( -1.23, -np.pi/2 +np.pi, 3,4 ,dimension).matrix, z)# t flip

#---
#logical 03
z = matmul( R( np.pi, -np.pi/2 +np.pi, 1,2 ,dimension).matrix, z)
z = matmul( R( -np.pi, -np.pi/2 -np.pi, 2,4 ,dimension).matrix, z)# t flip

z = matmul( R( -1.04, -np.pi/2, 3,4 ,dimension).matrix, z)# t flip
#---
#logical 04
z = matmul( R( np.pi, -np.pi/2 +np.pi, 0,4 ,dimension).matrix, z) # pi and pi/2

z = matmul( R( -0.92729521, -np.pi/2 +np.pi, 3,4 ,dimension).matrix, z)# t flip


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

match_graph_stateP2L4 = abs( matmul(  match_graph_stateP2L3, R( np.pi, -np.pi/2 +np.pi, 0,4 ,dimension).matrix.T.conj()) )
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

#z = matmul( Rz(np.pi, 4, dimension).matrix, z)
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

z = matmul( match_graph_stateP2L4, z)


print(z.round(3))
print()
print(zl.round(3))
print()
print( (np.abs(z - zl) < 1e-6).all() )



[[ 1.   +0.j     0.001+0.001j -0.   -0.001j -0.   +0.001j  0.001-0.001j]
 [ 0.   +0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   +0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.   -0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

[[ 1.   -0.j     0.001+0.001j -0.   -0.001j -0.   +0.001j  0.001-0.001j]
 [ 0.   -0.j    -0.219+0.301j -0.572+0.186j -0.572-0.186j -0.219-0.301j]
 [ 0.   -0.j    -0.534+0.041j  0.078-0.455j  0.078+0.455j -0.534-0.041j]
 [ 0.003-0.j    -0.378-0.426j  0.056+0.416j  0.056-0.416j -0.378+0.426j]
 [ 0.   -0.j     0.154-0.476j -0.404-0.293j -0.404+0.293j  0.154+0.476j]]

True


In [5]:
import numpy as np
def newMod(a, b=2 * np.pi):
    res = np.mod(a, b)
    return res if not res else res - b if a < 0 else res

def Pi_mod(a):
    a = newMod(a)

    if (a > 0 and a > np.pi):
        a = a - 2 * np.pi
    elif (a < 0 and abs(a) > np.pi):
        a = 2 * np.pi + a
    return a


print(Pi_mod(-9))
print(Pi_mod(4))
print(Pi_mod(18))
print(Pi_mod(6))
print(Pi_mod(8))



-2.7168146928204138
-2.2831853071795862
-0.8495559215387587
-0.28318530717958623
1.7168146928204138
