In [274]:

#PUT THIS FILE IN THE SAME FOLDER OF THE PROJECT DOWNLOADED


from src.circuit.Rotations import *
from src.evaluation.Pauli import H, S, X
from src.utils.r_utils import matmul
import numpy as np

In [275]:
def get_perm_matrix(dimension, nodes, mapping):
    perm = np.zeros((dimension, dimension))

    for i in range(dimension):
        a = [0 for i in range(dimension)]
        b = [0 for i in range(dimension)]
        a[nodes[i]] = 1
        b[mapping[i]] = 1
        narr = np.array(a)
        marr = np.array(b)
        perm = perm + np.outer(marr, narr)

    return perm

fix = get_perm_matrix(3, [0,1,2], [2, 0, 1])
print(fix)
fix2 = get_perm_matrix(3, [0,1,2], [2, 1, 0])
print(fix2)

print(matmul(fix,fix))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [278]:
dimension = 3

H1 = H( dimension )
X1= X( dimension )
S1 = S( dimension)
HS = matmul(H1.matrix, S1.matrix) 



In [279]:
print(H1.matrix)

match_graph_state = get_perm_matrix(3, [0,1,2], [2, 0, 1])

H1n = matmul( match_graph_state , H1.matrix)
H1n

[[ 0.57735027+0.j   0.57735027+0.j   0.57735027+0.j ]
 [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]]


array([[ 0.57735027+0.j , -0.28867513+0.5j, -0.28867513-0.5j],
       [ 0.57735027+0.j , -0.28867513-0.5j, -0.28867513+0.5j],
       [ 0.57735027+0.j ,  0.57735027+0.j ,  0.57735027+0.j ]])

In [298]:
t1 = matmul(R( np.pi, -np.pi/2, 0, 1 ,dimension).matrix.round(4), H1n)#R12->10
t1.round(2)

array([[ 0.58+0.j , -0.29-0.5j, -0.29+0.5j],
       [-0.58+0.j ,  0.29-0.5j,  0.29+0.5j],
       [ 0.58+0.j ,  0.58+0.j ,  0.58+0.j ]])

In [304]:
match_graph_state = get_perm_matrix(3, [0,1,2], [2, 1, 0])

t1= matmul(match_graph_state, t1)

t2 = matmul(R( -np.pi/2, np.pi/2 + np.pi , 0, 1 ,dimension).matrix.round(4), t1 )#R12->10

t2= matmul(match_graph_state.T, t2)

t2.round(2)

array([[ 0.58+0.j  ,  0.58+0.j  ,  0.58+0.j  ],
       [ 0.  +0.j  , -0.  -0.71j,  0.  +0.71j],
       [ 0.82+0.j  , -0.41+0.j  , -0.41+0.j  ]])

In [305]:

t3 = matmul(R( np.pi, -np.pi/2+np.pi, 0, 1 ,dimension).matrix.round(4), t2 )#R12->10
t3.round(2)


array([[ 0.  +0.j  ,  0.  +0.71j, -0.  -0.71j],
       [ 0.58+0.j  ,  0.58+0.j  ,  0.58+0.j  ],
       [ 0.82+0.j  , -0.41+0.j  , -0.41+0.j  ]])

In [307]:
match_graph_state = get_perm_matrix(3, [0,1,2], [2, 0, 1])

t3= matmul(match_graph_state, t3)

t4 = matmul(R( -1.23 , np.pi/2+2*np.pi , 0, 2 ,dimension).matrix.round(4), t3 )#R12->10

t4= matmul(match_graph_state.T, t4)

print(t4.round(2))

[[ 0.33+0.j   -0.67+0.j   -0.67+0.j  ]
 [ 0.94+0.j    0.24+0.j    0.24+0.j  ]
 [ 0.  +0.j    0.  +0.71j -0.  -0.71j]]


In [293]:
match_graph_state = get_perm_matrix(3, [0,1,2], [2, 0, 1])

t4= matmul(match_graph_state.T, t4)

t5 = matmul( R( np.pi/2, -4*np.pi, 1, 2 ,dimension).matrix.round(4), t4 )#R12->10

t5= matmul(match_graph_state.T, t5)
t5.round(2)


array([[ 0.24-0.67j,  0.38-0.32j,  0.09+0.49j],
       [ 0.  +0.j  ,  0.61+0.35j,  0.61-0.35j],
       [ 0.67-0.24j, -0.49-0.09j,  0.32-0.38j]])

In [109]:
t6 = matmul( Rz( 2.6100, 0, dimension).matrix.round(4), t5 )#R12->10
t6.round(2)

####### add Rz

array([[-0.25-0.43j, -0.5 -0.j  , -0.36+0.61j],
       [ 0.25-0.43j, -0.25-0.43j,  0.71+0.j  ],
       [-0.35+0.61j, -0.35-0.61j,  0.  +0.j  ]])

In [602]:
t7 = matmul( Rz( 2.09 , 1, dimension).matrix.round(4), t6 )#R12->10
t7.round(2)

array([[-0.86-0.51j, -0.  +0.j  ,  0.  -0.j  ],
       [-0.  -0.j  ,  1.  +0.j  , -0.  +0.j  ],
       [ 0.  -0.j  ,  0.  +0.j  , -0.87+0.5j ]])

In [622]:
f = H1.matrix
print(f.round(3))
print()
f = matmul( R( np.pi, -np.pi/2, 0, 1,dimension).matrix, f)

print(f.round(3))
print()

f = matmul(Rz(np.pi,1,dimension).matrix, f)
f.round(4)

[[ 0.577+0.j   0.577+0.j   0.577+0.j ]
 [ 0.577+0.j  -0.289+0.5j -0.289-0.5j]
 [ 0.577+0.j  -0.289-0.5j -0.289+0.5j]]

[[ 0.577-0.j  -0.289+0.5j -0.289-0.5j]
 [-0.577-0.j  -0.577-0.j  -0.577-0.j ]
 [ 0.577+0.j  -0.289-0.5j -0.289+0.5j]]



array([[ 0.5774-0.j , -0.2887+0.5j, -0.2887-0.5j],
       [ 0.5774+0.j ,  0.5774+0.j ,  0.5774+0.j ],
       [ 0.5774+0.j , -0.2887-0.5j, -0.2887+0.5j]])

In [54]:
#############################################

In [608]:
f = np.identity(3, dtype='complex')
#f = np.dot(np.identity(3, dtype='complex'), Rz( 0.3, 1, 3).matrix )


f = matmul(R( np.pi, -np.pi/2,             0, 1,dimension).matrix,  f)
print(f.round(3))
print()
f = matmul(R(-np.pi/2 , np.pi/2 + np.pi ,  1, 2,dimension).matrix, f)
print(f.round(3))
print()
f = matmul(R( np.pi, np.pi/2 - np.pi,     0, 1,dimension).matrix,  f)
print(f.round(3))
print("-----------")
f = matmul(R( -1.23,   -np.pi/2 - 2*np.pi ,  1, 2,dimension).matrix, f)
print(f.round(3))
print()
f = matmul(R( np.pi/2, -2*np.pi - 2*np.pi ,  0, 1,dimension).matrix, f)
print(f.round(3))
print()

#f = np.dot(Rz( 2.61, 0, 3).matrix, f)
#f = np.dot(Rz( 2.09 , 1, 3).matrix,f)
#f = np.dot(Rz( -np.pi, 2, 3).matrix, f)

f.round(3)

[[ 0.+0.j  1.-0.j  0.+0.j]
 [-1.-0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j]]

[[ 0.   +0.j  1.   -0.j  0.   +0.j]
 [-0.707-0.j  0.   +0.j -0.707-0.j]
 [-0.707+0.j  0.   -0.j  0.707+0.j]]

[[-0.707+0.j  0.   -0.j -0.707-0.j]
 [-0.   -0.j -1.   +0.j -0.   -0.j]
 [-0.707+0.j  0.   -0.j  0.707+0.j]]
-----------
[[-0.707+0.j  0.   -0.j -0.707-0.j]
 [ 0.408-0.j -0.817+0.j -0.408+0.j]
 [-0.578+0.j -0.577-0.j  0.578-0.j]]

[[-0.5  -0.288j  0.   +0.578j -0.5  +0.288j]
 [ 0.288+0.5j   -0.578-0.j    -0.288+0.5j  ]
 [-0.578+0.j    -0.577-0.j     0.578-0.j   ]]



array([[-0.5  -0.288j,  0.   +0.578j, -0.5  +0.288j],
       [ 0.288+0.5j  , -0.578-0.j   , -0.288+0.5j  ],
       [-0.578+0.j   , -0.577-0.j   ,  0.578-0.j   ]])

In [534]:
R( -1.23,np.pi/2 , 0, 2, dimension).matrix.round(3)

array([[ 0.817+0.j,  0.   +0.j,  0.577+0.j],
       [ 0.   +0.j,  1.   +0.j,  0.   +0.j],
       [-0.577+0.j,  0.   +0.j,  0.817+0.j]])

In [24]:
R( 3.14, 0, 0, 1 ,dimension).matrix.round(2)

array([[0.+0.j, 0.-1.j, 0.+0.j],
       [0.-1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [30]:
matmul(f, X1.matrix)

array([[ 0.+0.j,  0.+0.j,  1.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j]])

In [31]:
matmul(Rz( 3.14, 0 , dimension).matrix, matmul(f, X1.matrix)).round(2)

array([[ 0.+0.j,  0.+0.j, -1.-0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j],
       [ 1.+0.j,  0.+0.j,  0.+0.j]])

In [42]:
R( 1.23, -1.23, 0, 1,dimension).matrix.round(2)

array([[ 0.82+0.j  ,  0.54-0.19j,  0.  +0.j  ],
       [-0.54-0.19j,  0.82+0.j  ,  0.  +0.j  ],
       [ 0.  +0.j  ,  0.  +0.j  ,  1.  +0.j  ]])

In [92]:
"""
print(R( 3.14,-1.57, 0, 2,dimension).matrix.round(2))
print()
print(R( 1.23, -1.23, 0, 1,dimension).matrix.round(2))
print()
print(matmul( R( 1.23, -1.23, 0, 1,dimension).matrix.round(2),R(3.14, -1.57, 0, 2,dimension).matrix).round(2))
print()
print(matmul( R( 1.23, 1.23, 0, 1,dimension).matrix.round(2),R(3.14, -1.57, 0, 2,dimension).matrix).round(2))
print()
"""
print(matmul(R( 3.14, 1.57, 0, 2 ,dimension).matrix, matmul(R( 1.23, 1.23, 0, 1,dimension).matrix, R( 3.14, -1.57, 0, 2,dimension).matrix.round(2))).round(2))
print()
j = matmul(R( 3.14, -1.57, 0, 2 ,dimension).matrix, matmul(R( 1.23, 1.23, 0, 1,dimension).matrix, R( 3.14, -1.57, 0, 2,dimension).matrix.round(2))).round(2)
print(j)
####################
print()
#print(matmul(R( 3.14, 1.57, 0, 2 ,dimension).matrix, j).round(2))
#print(j)
################################
print()

k = matmul(Rz( 3.14, 2 , dimension).matrix, j).round(2)

print(k)
print()
print(matmul(Rz( 3.14, 0 , dimension).matrix, k).round(2))


[[ 1.  +0.j   -0.  -0.j    0.  +0.j  ]
 [ 0.  +0.j    0.82+0.j    0.54-0.19j]
 [-0.  +0.j   -0.54-0.19j  0.82-0.j  ]]

[[-1.  +0.j   -0.  -0.j    0.  +0.j  ]
 [ 0.  +0.j    0.82+0.j    0.54-0.19j]
 [-0.  +0.j    0.54+0.19j -0.82-0.j  ]]


[[-1.  +0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.82+0.j    0.54-0.19j]
 [ 0.  +0.j   -0.54-0.19j  0.82+0.j  ]]

[[ 1.  +0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.82+0.j    0.54-0.19j]
 [ 0.  +0.j   -0.54-0.19j  0.82+0.j  ]]


In [3]:
#
#  Imagine a graph like this (L=logical, P=physical)
# (L0/P2) <-> (L2/P0) <-> (L1/P1)
#


R0 = R( 1.57, -1.57, 0, 1 ,dimension) #R12->10

R1 = R(-np.pi, -1.57, 0, 1 ,dimension) #PI PULSE

R2 = R( 1.91, -1.57, 0, 2 ,dimension) #ROUTED R01

R1dag = R(np.pi, -1.57, 0, 1 ,dimension) #PI PULSE DAG

R3 = R( 1.57, 0, 0, 1 ,dimension) #R12->10

##################################

Rz0 = Rz(-1.0471975511, 0 , dimension)# RZ OF ENTRY i=1

Rz1 = Rz(1.5707, 1, dimension) # RZ OF ENTRY i=2


In [4]:
R0.matrix.round(2)

array([[ 0.71+0.j,  0.71+0.j,  0.  +0.j],
       [-0.71+0.j,  0.71+0.j,  0.  +0.j],
       [ 0.  +0.j,  0.  +0.j,  1.  +0.j]])

In [5]:
R1.matrix.round(7)

array([[ 0.       +0.j       , -0.9999997-0.0007963j,
         0.       +0.j       ],
       [ 0.9999997-0.0007963j,  0.       +0.j       ,
         0.       +0.j       ],
       [ 0.       +0.j       ,  0.       +0.j       ,
         1.       +0.j       ]])

In [6]:
R2.matrix.round(7)

array([[ 0.5776088+0.j       ,  0.       +0.j       ,
         0.8163135+0.0006501j],
       [ 0.       +0.j       ,  1.       +0.j       ,
         0.       +0.j       ],
       [-0.8163135+0.0006501j,  0.       +0.j       ,
         0.5776088+0.j       ]])

In [7]:
R1dag.matrix.round(7)

array([[ 0.       +0.j       ,  0.9999997+0.0007963j,
         0.       +0.j       ],
       [-0.9999997+0.0007963j,  0.       +0.j       ,
         0.       +0.j       ],
       [ 0.       +0.j       ,  0.       +0.j       ,
         1.       +0.j       ]])

In [8]:
R3.matrix.round(7)

array([[0.7073883+0.j       , 0.       +0.7068252j, 0.       +0.j       ],
       [0.       +0.7068252j, 0.7073883+0.j       , 0.       +0.j       ],
       [0.       +0.j       , 0.       +0.j       , 1.       +0.j       ]])

In [9]:
Rz0.matrix.round(7)

array([[0.5+0.8660254j, 0. +0.j       , 0. +0.j       ],
       [0. +0.j       , 1. +0.j       , 0. +0.j       ],
       [0. +0.j       , 0. +0.j       , 1. +0.j       ]])

In [10]:
Rz1.matrix.round(7)

array([[1.00e+00+0.j, 0.00e+00+0.j, 0.00e+00+0.j],
       [0.00e+00+0.j, 9.63e-05-1.j, 0.00e+00+0.j],
       [0.00e+00+0.j, 0.00e+00+0.j, 1.00e+00+0.j]])

### reconstruct

In [11]:
print(target.round(5))
ph = matmul(R0.matrix, target).round(2)
ph

[[ 0.57735+0.j  -0.28868+0.5j  0.57735+0.j ]
 [ 0.57735+0.j  -0.28868-0.5j -0.28868-0.5j]
 [ 0.57735+0.j   0.57735-0.j  -0.28868+0.5j]]


array([[ 0.82+0.j  , -0.41+0.j  ,  0.2 -0.35j],
       [ 0.  +0.j  , -0.  -0.71j, -0.61-0.35j],
       [ 0.58+0.j  ,  0.58-0.j  , -0.29+0.5j ]])

In [12]:
ph = matmul(R1.matrix, ph).round(2)
ph

array([[ 0.  +0.j  , -0.  +0.71j,  0.61+0.35j],
       [ 0.82-0.j  , -0.41+0.j  ,  0.2 -0.35j],
       [ 0.58+0.j  ,  0.58+0.j  , -0.29+0.5j ]])

In [13]:
ph = matmul(R2.matrix, ph).round(2)
ph

array([[ 0.47+0.j  ,  0.47+0.41j,  0.12+0.61j],
       [ 0.82+0.j  , -0.41+0.j  ,  0.2 -0.35j],
       [ 0.34+0.j  ,  0.33-0.58j, -0.67+0.j  ]])

In [14]:
ph = matmul(R1dag.matrix, ph).round(2)
ph

array([[ 0.82+0.j  , -0.41-0.j  ,  0.2 -0.35j],
       [-0.47+0.j  , -0.47-0.41j, -0.12-0.61j],
       [ 0.34+0.j  ,  0.33-0.58j, -0.67+0.j  ]])

In [15]:
ph = matmul(R3.matrix, ph).round(2)
ph

array([[ 0.58-0.33j, -0.  -0.33j,  0.57-0.33j],
       [-0.33+0.58j, -0.33-0.58j,  0.16-0.29j],
       [ 0.34+0.j  ,  0.33-0.58j, -0.67+0.j  ]])

In [16]:
ph = matmul(Rz0.matrix, ph).round(4)
ph

array([[ 0.5758+0.3373j,  0.2858-0.165j ,  0.5708+0.3286j],
       [-0.33  +0.58j  , -0.33  -0.58j  ,  0.16  -0.29j  ],
       [ 0.34  +0.j    ,  0.33  -0.58j  , -0.67  +0.j    ]])

In [17]:
print(HS.matrix.round(5))

[[ 0.57735+0.j  -0.28868+0.5j  0.57735+0.j ]
 [ 0.57735+0.j  -0.28868-0.5j -0.28868-0.5j]
 [ 0.57735+0.j   0.57735-0.j  -0.28868+0.5j]]


In [24]:
nodes=[0,1,2]
mapping = [2,1,0]

In [27]:

perm = np.zeros((3, 3))

for i in range(3):
    a = [0 for i in range(3)]
    b = [0 for i in range(3)]
    a[nodes[i]] = 1
    b[mapping[i]] = 1
    narr = np.array(a)
    marr = np.array(b)
    perm = perm + np.outer(marr , narr)
    print(perm)


[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [28]:
perm

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])